apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kube
provisioner: kubernetes.io/rbd
parameters:
  monitors: 172.21.0.5:6789, 172.21.0.6:6789, 172.21.0.7:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: "kube-system"
  pool: kube
  userId: user
  userSecretName: ceph-secret-user
